### ISSUE TITLE
Potential path mismanagement in Linux Dedicated Servers

### ISSUE THREAD

**Issue by theCrius** [FakeFishGames/Barotrauma#10112]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I've tried to run a dedicated server using only Lua for Barotrauma and Neurotrauma.
Server starts, no issue, can connect, all the good things.

However, when I start the round, the server print out this:

```
Coroutine Barotrauma.Networking.GameServer+<StartGame>d__89 threw an exception: Could not find a part of the path '/barotrauma/Daedalic Entertainment GmbH/Barotrauma/Daedalic Entertainment GmbH/Barotrauma'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFileSystemEntries(String path)
   at Barotrauma.ToolBox.CorrectFilenameCase(String filename, Boolean& corrected, String directory) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/ToolBox.cs:line 131
   at Barotrauma.ToolBox.CleanUpPathCrossPlatform(String path, Boolean correctFilenameCase, String directory) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/ToolBox.cs:line 660
   at Barotrauma.ContentPath.get_Value() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/ContentManagement/ContentPath.cs:line 66
   at Barotrauma.RagdollParams.GetFolder(ContentXElement root, String filePath) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 116
   at Barotrauma.RagdollParams.GetFolder(Identifier speciesName, ContentPackage contentPackage) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 111
   at Barotrauma.RagdollParams.GetRagdollParams[T](Identifier speciesName, String fileName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 154
   at Barotrauma.HumanRagdollParams.GetRagdollParams(Identifier speciesName, String fileName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 17
   at Barotrauma.CharacterInfo.get_Ragdoll() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/CharacterInfo.cs:line 523
   at Barotrauma.HumanoidAnimController.get_HumanRagdollParams() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 32
   at Barotrauma.HumanoidAnimController.get_RagdollParams() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 15
   at Barotrauma.Ragdoll..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/Ragdoll.cs:line 447
   at Barotrauma.AnimController..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/AnimController.cs:line 179
   at Barotrauma.HumanoidAnimController..ctor(Character character, String seed, HumanRagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 195
   at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1332
   at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1141
   at Barotrauma.Networking.GameServer.StartGame(SubmarineInfo selectedSub, SubmarineInfo selectedShuttle, GameModePreset selectedMode, CampaignSettings settings)+MoveNext()
   at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 198
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 231
```

Now, if you read the first line, it mention this path:

`/barotrauma/Daedalic Entertainment GmbH/Barotrauma/Daedalic Entertainment GmbH/Barotrauma`

The first `/barotrauma` is simply the directory in which the server is installed, so don't care about it particularly now.
The rest is more interesting:

`/barotrauma` - `/Daedalic Entertainment GmbH/Barotrauma` - `/Daedalic Entertainment GmbH/Barotrauma`

I separated the two chunks for legibility. It seems like somewhere the path to reach the files listed afterwards is duplicated.  
Now initially I thought it was an issue with Neurotrauma but after checking the source code and having an exchange with the maintainer(s), it doesn't seems to be the case. The mod itself simply refers to the various locations via variables that, I suppose, I set by the game itself at runtime.

Interesting tidbit, If I run this configuration from my windows machine, there is no issue, no bug, no error. It only happen on linux. Considering the anomaly I suspect that somewhere there is a reference that is `relative` path and assumed as `absolute` instead which work on windows but will not work on linux.

### Reproduction steps

If you want a reproducible environment, you can use my docker image: https://github.com/theCrius/barotrauma-docker

And if you want to see the error "fixed" simply add in the [Dockerfile](https://github.com/theCrius/barotrauma-docker/blob/main/Dockerfile) between line 67 and 68 these lines:

```
# TEST x Neurotrauma
RUN mkdir -p "$INSTALL_LOC/Daedalic Entertainment GmbH/Barotrauma/Daedalic Entertainment GmbH"
RUN ln -s  "$INSTALL_LOC/Daedalic Entertainment GmbH/Barotrauma/" "$INSTALL_LOC/Daedalic Entertainment GmbH/Barotrauma/Daedalic Entertainment GmbH/Barotrauma"
# /TEST
```

If you want a config_player.xml file to add on the fly, [here](https://pastebin.com/raw/95ZLwqwn).  
You'll need to add the neurotrauma mod manually, I've been waiting for Barotrauma to be in its "released" state before committing to write a script that download and install mods.

### Bug prevalence

Happens every time I play

### Version

0.19.11.0

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Thank you for the report! The stack trace seems to suggest this might be related to https://github.com/Regalis11/Barotrauma/issues/9985 (an issue which should be fixed in the unstable branch), but I still think we need to give this a test and verify that's the case.

**Comment by theCrius** [comment]
Great stuff, glad it was already reported. Hopefully we get an update soon. My group is eager to start a new campaign and we wanted to try some mods this time :)

**Comment by theCrius** [comment]
Tried with the latest version (0.19.14) and I still get this error:

```
barotrauma_1  | [10/20/2022 18:18:57]
barotrauma_1  |   Client "Crius" started the round.
barotrauma_1  | [10/20/2022 18:18:57]
barotrauma_1  |   Starting a new round...
barotrauma_1  | Level identifier: coldcavernsbasic
barotrauma_1  | Generating an outpost for the end of the level... (Location: Newellstead Fortification, level type: LocationConnection)
barotrauma_1  | WARNING: Entity events have been created during level generation. Events should not be created until the round is fully initialized.
barotrauma_1  | [10/20/2022 18:18:59]
barotrauma_1  |   Game mode: Sandbox
barotrauma_1  | [10/20/2022 18:18:59]
barotrauma_1  |   Submarine: Humpback
barotrauma_1  | [10/20/2022 18:18:59]
barotrauma_1  |   Level seed: 13hVwSJo
barotrauma_1  | Coroutine Barotrauma.Networking.GameServer+<StartGame>d__89 threw an exception: Could not find a part of the path '/barotrauma/Daedalic Entertainment GmbH/Barotrauma/Daedalic Entertainment GmbH/Barotrauma'.
barotrauma_1  |    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
barotrauma_1  |    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
barotrauma_1  |    at System.IO.Enumeration.FileSystemEnumerableFactory.UserEntries(String directory, String expression, EnumerationOptions options)
barotrauma_1  |    at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
barotrauma_1  |    at System.IO.Directory.GetFileSystemEntries(String path)
barotrauma_1  |    at Barotrauma.ToolBox.CorrectFilenameCase(String filename, Boolean& corrected, String directory) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/ToolBox.cs:line 131
barotrauma_1  |    at Barotrauma.ToolBox.CleanUpPathCrossPlatform(String path, Boolean correctFilenameCase, String directory) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Utils/ToolBox.cs:line 660
barotrauma_1  |    at Barotrauma.ContentPath.get_Value() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/ContentManagement/ContentPath.cs:line 66
barotrauma_1  |    at Barotrauma.RagdollParams.GetFolder(ContentXElement root, String filePath) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 116
barotrauma_1  |    at Barotrauma.RagdollParams.GetFolder(Identifier speciesName, ContentPackage contentPackage) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 111
barotrauma_1  |    at Barotrauma.RagdollParams.GetRagdollParams[T](Identifier speciesName, String fileName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 154
barotrauma_1  |    at Barotrauma.HumanRagdollParams.GetRagdollParams(Identifier speciesName, String fileName) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Params/Ragdoll/RagdollParams.cs:line 17
barotrauma_1  |    at Barotrauma.CharacterInfo.get_Ragdoll() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/CharacterInfo.cs:line 523
barotrauma_1  |    at Barotrauma.HumanoidAnimController.get_HumanRagdollParams() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 32
barotrauma_1  |    at Barotrauma.HumanoidAnimController.get_RagdollParams() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 15
barotrauma_1  |    at Barotrauma.Ragdoll..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/Ragdoll.cs:line 447
barotrauma_1  |    at Barotrauma.AnimController..ctor(Character character, String seed, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/AnimController.cs:line 179
barotrauma_1  |    at Barotrauma.HumanoidAnimController..ctor(Character character, String seed, HumanRagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/HumanoidAnimController.cs:line 195
barotrauma_1  |    at Barotrauma.Character..ctor(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, RagdollParams ragdollParams) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1332
barotrauma_1  |    at Barotrauma.Character.Create(CharacterPrefab prefab, Vector2 position, String seed, CharacterInfo characterInfo, UInt16 id, Boolean isRemotePlayer, Boolean hasAi, Boolean createNetworkEvent, RagdollParams ragdoll) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Character.cs:line 1141
barotrauma_1  |    at Barotrauma.Networking.GameServer.StartGame(SubmarineInfo selectedSub, SubmarineInfo selectedShuttle, GameModePreset selectedMode, CampaignSettings settings)+MoveNext()
barotrauma_1  |    at Barotrauma.CoroutineManager.PerformCoroutineStep(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 199
barotrauma_1  |    at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in <DEV>/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 257
barotrauma_1  | Attempted to access a potentially removed ragdoll. Character: Crius, id: 2032, removed: True, ragdoll removed: False
barotrauma_1  |    at System.Environment.get_StackTrace()
barotrauma_1  |    at Barotrauma.Ragdoll.get_Limbs() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/Ragdoll.cs:line 63
barotrauma_1  |    at Barotrauma.Ragdoll.Remove() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/Ragdoll.cs:line 1966
barotrauma_1  |    at Barotrauma.Ragdoll.RemoveAll() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Characters/Animation/Ragdoll.cs:line 2004
barotrauma_1  |    at Barotrauma.Submarine.Unload() in <DEV>/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs:line 1724
barotrauma_1  |    at Barotrauma.Networking.GameServer.EndGame(TransitionType transitionType, Boolean wasSaved) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 2717
barotrauma_1  |    at Barotrauma.Networking.GameServer.Update(Single deltaTime) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 510
barotrauma_1  |    at Barotrauma.GameMain.Run() in <DEV>/Barotrauma/BarotraumaServer/ServerSource/GameMain.cs:line 345
barotrauma_1  |    at Barotrauma.Program.Main(String[] args) in <DEV>/Barotrauma/BarotraumaServer/ServerSource/Program.cs:line 87
barotrauma_1  | [10/20/2022 18:19:00]
barotrauma_1  |   Round ended.
barotrauma_1  | WARNING: Received a REQUEST_STARTGAMEFINALIZE message. Game not started, ignoring the message.
barotrauma_1  | WARNING: Received a REQUEST_STARTGAMEFINALIZE message. Game not started, ignoring the message.
```

To give more context, the server starts. The Lobby starts and you can join and do whatever you would normally do. When you click "start" the server load and then kick you back to lobby.
The logs are clear enough but I thought to put it more explicitly.

Again, this is a linux server, running on docker container. The image is from [here](https://hub.docker.com/r/steamcmd/steamcmd) and it's a steamcmd based off Ubuntu 20.

**Comment by theCrius** [comment]
Guys, this seemed to be fixed but after updating the server side today (took a break for the festivities) I can see that another mod have issues.

The error reported is:

```
Failed to load "Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2764140582/Items/Decor Override.xml": Could not find a part of the path '/barotrauma/Daedalic Entertainment GmbH/Barotrauma/Daedalic Entertainment GmbH/Barotrauma'.
```

you can see the same pattern repeated in `/barotrauma/Daedalic Entertainment GmbH/Barotrauma/Daedalic Entertainment GmbH/Barotrauma`

I'm currently updating the docker file due to [another bug](https://github.com/Regalis11/Barotrauma/issues/10806) but you will be able to use this [docker configuration](https://github.com/theCrius/barotrauma-docker/) for testing by adding this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2764140582

**Comment by 3e849f2e5c** [comment]
Collecting some notes about my recent look into this

I was unable to repro the exact same crash but I encountered few issues attempting to run the docker image on a fresh installation of Debian 12

- The UID and GID variable stuff is broken I had to manually edit the image to define them and setting the exports as stated in the readme weren't being picked up ($UID is also a readonly variable so defining it does nothing)
- Starting the server just crashes on launch since the docker image puts the `Daedalic Entertainment GmbH` directory to `/barotrauma` when the server is configured to look for it in `Environment.SpecialFolder.LocalApplicationData` which is defined by `$XDG_DATA_HOME` environment variable on Linux and set to `~/.local/share` by default, adding `ENV XDG_DATA_HOME="/barotrauma"` to the Dockerfile made the server run just fine

**Comment by Jasontti** [comment]
There's been no new information in 2 years, closing ticket as stale.
