### ISSUE TITLE
Issue Acquiring Husk Symbiosis and mission text problems

### ISSUE THREAD

**Issue by Alapaca88** [FakeFishGames/Barotrauma#13004]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Rescuing Jacov Cobra mission have faulty texts. I have added pictures of them.
https://i.ibb.co/2tHbVB3/1111.png
https://i.ibb.co/1JkCC6G/2222.png

Also after finishing the mission and attending the comunication no one got the Husk Symbiosis.

### Reproduction steps

1. Start Multiplayer Campaign.
2. Finish the Way to Ascension questline

### Bug prevalence

Just once

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.1.19.3 (Treacherous Tides Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Thank you for the report!

I've fixed the text issue now (commit in our private repository https://github.com/Regalis11/Barotrauma-development/commit/13d9fc403c08c05834f52f098bd238d5079648ec), but we still need to look in to the issue with the Husk Symbiosis. Sorry for the inconvenience!

**Comment by Alapaca88** [comment]
I have a backup save game just when we docked at Rescuing Jacov mission.
https://i.ibb.co/wJMwKMP/Jacov-Saved.png

The message is still the same.

**Comment by Regalis11** [comment]
The fix hasn't been released yet, but will hopefully be included in the next patch/update! :)

**Comment by Alapaca88** [comment]
I'm sorry, I don't know what I was thinking. I will try to test this ticket out after patch.

**Comment by Jasontti** [comment]
Tested.

Could not reproduce.
Tried to do it as organicly as possible in single player and multiplayer.
Tested in current stable and internal dev build.

We can leave this ticket up, for some while, to see if another issues come up.

**Comment by Regalis11** [comment]
No known steps to repro, closing
