### ISSUE TITLE
Small mudraptor eggs spawning in nest missions

### ISSUE THREAD

**Issue by Vykn** [FakeFishGames/Barotrauma#13505]
In destroy nest missions, if the nest is a mudraptor nest, some of the eggs will be replaced by the small version of the egg which can be picked up. This occurs even with traitors turned off.
It doesn't interfere with the functionality of the mission - you can still complete the objective. The issue is in that finding the eggs can become very difficult when they are so small. 

An illustration:

![image](https://github.com/FakeFishGames/Barotrauma/assets/37850646/1b77a836-3ad2-488e-b0bb-668a63230f36)

Even using `devmode` to light up the area and remove the LOS effects, it's still very hard to spot. In the poor visibility of a real cave where you don't know where the eggs are, completing the mission can be very difficult.

It would be good if these small eggs didn't spawn in non-traitor missions, or were somehow made more visible (e.g. making them glow underwater or something)

### Reproduction steps
1. Host mission mode, select nest mission (I tested at 100% difficulty, on a variety of seeds - occurred every time)
2. Restart until it is specifically a mudraptor nest
3. Swim into the nest and clear out the enemies
4. Look for the eggs, notice that some are small eggs and difficult to spot

Occurs in v1.2.8.0 (Winter Update hotfix 2) and v1.2.12.0 (Unstable ROS)

**Comment by Regalis11** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/commit/120e5c1fd8848be53481974740a2f31eab9f7845

**Comment by ubertpendragon** [comment]
Not fixed! 

mudraptornest and mudraptornesthard still use small eggs
