### ISSUE TITLE
Sprite Bleed On Clothes Rack

### ISSUE THREAD

**Issue by brand175** [FakeFishGames/Barotrauma#13544]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On the sides
![Barotrauma Screenshot 2024 03 12 - 15 35 28 46](https://github.com/FakeFishGames/Barotrauma/assets/20964160/58d66642-bbcc-4df9-a3a3-8ad2434b2317)

### Reproduction steps

Open Sub editor

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.2.8.0 (Winter Update hotfix 2)

### Which operating system did you encounter this bug on?

Windows

**Comment by NotWendy** [comment]
It affects a bunch of sprites currently. Box4 (one pixel line on the left side), decorative wire (a rolled up wire on the floor, with two ends going up), basic platform (one pixel line at the bottom), fliers (one pixel line at the top), and many more I can't remember off the top of my head.
Some wall textures have blank one pixel lines in the middle, which show up if you make the wall long enough. Affects inside walls, one of the outpost manager backgrounds, and possibly some other sprites.

These small imperfections are sometimes barely visible, other times they're rendered as noticeable, thick lines. They appear both with texture compression on and off. Here are some screenshots.

![image](https://github.com/FakeFishGames/Barotrauma/assets/47554589/a420492d-7af9-4334-9353-1a184f09f88e)
![image2](https://github.com/FakeFishGames/Barotrauma/assets/47554589/7c155ddd-523c-459c-960f-c82a7828d8a1)
![image3](https://github.com/FakeFishGames/Barotrauma/assets/47554589/0ad03368-a269-436a-809e-5e7fd6fcdaa6)
![image4](https://github.com/FakeFishGames/Barotrauma/assets/47554589/5ac27d7a-6774-4c31-834f-67ca4b1bd364)

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/8365f4152cff349e17bd0b45f6d32f43d53fbb75

**Comment by NotWendy** [comment]
Huge, thank you. But don't forget the fliers! (I think you did, based on the commit message.)
They caught one pixel of the bench above them.
![Image](https://github.com/FakeFishGames/Barotrauma/assets/47554589/0fd8dc9b-0eef-4cc5-8fcd-2ff04146539f)

**Comment by Rokvach** [comment]
I still see some bleeding at the bottom of the Clothes Rack
![image](https://github.com/FakeFishGames/Barotrauma/assets/7299826/04884bab-fdc5-4bd5-8a3f-6d4032b030e5)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
