### ISSUE TITLE
Infinite missions upon reloading

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#13880]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/13879

<div type='discussions-op-text'>

<sup>Originally posted by **RooneyRoll** April 28, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When all the possible missions are taken from an outpost if I save and then load the game the mission giving npc have new set of missions which I am able to accept.

### Reproduction steps

1. Dock and arrive at a station or outpost
2.  Go to the top and get the missions you can choose from
3. Save and quit the game
4. Load the game and repeat from step 2.

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Single player

### Version

v1.4.5.0 (Blood in the Water Update, hotfix 1)

### Which operating system did you encounter this bug on?

Linux

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/1f0383b2e92b197ab073d8ebc56840a295a9f918

**Comment by Rokvach** [comment]
Tested, in both singleplayer and multiplayer the fix does work if you leave the first outpost, but if you stay or even return to the first outpost you will still get infinite missions by saving and quitting. Moving back to main board ToDo.

**Comment by Jasontti** [comment]
Tested in: https://github.com/FakeFishGames/Barotrauma-development/pull/5257/commits/9549eb3bcb85ce5f0a7d6d9188e73059cf5de5c3

Tested in SP and MP
Tested steps provided
tested in couple outposts
saved before accepting all missions
saved before accepting missions

Could not replicate issue that Rockvach, but don't see that it was adressed in between.
Maybe this was moved to QA by mistake?

**Comment by itchyOwl** [comment]
Addressed in https://github.com/FakeFishGames/Barotrauma-development/pull/5257/commits/9549eb3bcb85ce5f0a7d6d9188e73059cf5de5c3

**Comment by Jasontti** [comment]
My mistake, no issues found.
Closing as completed.

**Comment by A2ur3** [comment]
This issue persists in multiplayer. Saving and quitting, then reloading the save still allows you to take infinite missions from the station administrator. I've created a new discussion about it #16301
