### ISSUE TITLE
The Health UI displayes incorrectly When Head and Head attachments have different sourcerect and origin

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14650]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14646

<div type='discussions-op-text'>

<sup>Originally posted by **Raven-233486** September 16, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

The incorrect health UI
![image](https://github.com/user-attachments/assets/5a21b031-193c-4b0c-8dad-0a7dd003fe98)
![image](https://github.com/user-attachments/assets/2fb3a93b-ea37-40ee-b241-d7ddfe367335)
However, the character displays correctly:
![image](https://github.com/user-attachments/assets/28884922-ba1d-4d01-ab44-1ce680b8f884)
![image](https://github.com/user-attachments/assets/1a8b8b20-0ea1-4175-8b15-b0d8fc2120d5)

### Reproduction steps

Biff_W reported issue 12068 that headattachments' sourcerects are unchangeable last year and it had been fixed, here's the link: 
https://github.com/FakeFishGames/Barotrauma/issues/12068

However, the fix only covered character limb, not about the health interface.

Reproduction steps (Make hair and head have different sourcerects):
In human.xml:
```
      <Wearable type="Hair" commonness="0.05" >
        <sprite name="Hair 1" texture="%ModDir:2809175631%/Content/Characters/Human/Headattachments/Human_decor.png" sourcerect="0,0,240,480" origin="0.6125,0.3229" inheritorigin="false" inheritsourcerect="false" />
      </Wearable>
```
In HumanDefaultRagdoll.xml
```
<limb Name="Head (1)" ID="1" Type="Head" >
    <sprite texture="%ModDir:2809175631%/Content/Characters/Human/Human_[GENDER]_heads.png" sourcerect="0,0,160,228" depth="0.05" origin="0.6125,0.33" color="255,255,255,255" deadcolor="255,255,255,255" deadcolortime="0" ignoretint="False" />
    <tintmask texture="%ModDir:2809175631%/Content/Characters/Human/Human_[GENDER]_heads_mask.png" />
</limb>
```

### Bug prevalence

Happens every time I play

### Single player or multiplayer?

Single player

### Version

v1.5.9.2 (Summer Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/ee8c6f2f0b2fd92d32d3ed32ee5ac6064324b1d1

**Comment by ToumanLin** [comment]
This problem still haven't been fixed
https://github.com/FakeFishGames/Barotrauma/discussions/14646#discussioncomment-11023056

**Comment by Regalis11** [comment]
The fix unfortunately didn't make it to this update, we still need to review and test it internally before we can get it to a public build. Sorry for the inconvenience!

**Comment by Regalis11** [comment]
Merged, closing. Fix coming up in the next release!

**Comment by A2ur3** [comment]
@Regalis11 I have a similar issue #15722 that hair is misaligned in character creation menu
