### ISSUE TITLE
[Unstable] PvP mode - crash when attempting to change name on cooldown in lobby

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#14868]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/14862

<div type='discussions-op-text'>

<sup>Originally posted by **Ruberine** October 20, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When in PvP mode, a player attempted to change a name while on cooldown. The "You are not allowed to change your name this often. Please wait X seconds." message repeatedly appears until game crash. The outfit selection icon repeatedly flashes during this time.

### Reproduction steps

1. Start a multiplayer PvP lobby
2. Select Coalition or Separatist (error does not occur if unaffiliated)
3. Change your name
4. Change your name a second time while it is on cooldown

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Multiplayer hosted from the in-game menu (= using a listen server)

### Version

v1.6.17.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 10/20/2024 01:41:45)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

60D124F0E68F674E8D38345F619F4911

Game version 1.6.17.0 (ReleaseWindows, branch release/autumn-update, revision aa6050b27f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla (3758FF2)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateJobVariantTooltip(Barotrauma.JobPrefab, Barotrauma.CharacterTeamType, Int32, Boolean, Barotrauma.GUIComponent)
Stack trace: 
   at Barotrauma.NetLobbyScreen.CreateJobVariantTooltip(JobPrefab jobPrefab, CharacterTeamType team, Int32 variant, Boolean isPvPMode, GUIComponent parentSlot) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\NetLobbyScreen.cs:line 2808
   at Barotrauma.NetLobbyScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\NetLobbyScreen.cs:line 4024
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 942
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61

Last debug messages:
[10/20/2024 01:41:36] Lobby created!
[10/20/2024 01:41:04] Attempting to open ALC device "OpenAL Soft on Speakers (HyperX Cloud Stinger Core Wireless DTS)"
[10/20/2024 01:41:02] Logged in as ruberine (SteamID STEAM_1:0:549660146)
```
</div>

**Comment by Regalis11** [comment]
Note: I wasn't able to repro the crash, but there's definitely something wrong here: when you attempt to set your name when the name change cooldown is active, you'll start getting spammed with the "can't change name" chat message and can't change any of your preferences (job, team, character appearance).

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/d64b5bd5b3c6e738ed35c752d34685053dd1095c

**Comment by Ruberine** [comment]
> Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/d64b5bd5b3c6e738ed35c752d34685053dd1095c

@Regalis11 Bug does not seem to be fixed, still occurs in stable. Further testing shows that crash only occurs when attempting to change outfit. Video linked to prove (file size too large for Github, unlisted youtube video linked), same setup as per in the original issue, no mods were used, file integrity verified beforehand.

https://youtu.be/aoH0dFUzzAE

New crash report below:
<br></br>
<br></br>
Barotrauma Client crash report (generated on 10/22/2024 21:41:19)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

60D124F0E68F674E8D38345F619F4911

Game version 1.6.17.0 (ReleaseWindows, branch release/autumn-update, revision aa6050b27f)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla (3758FF2)
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.NetLobbyScreen
SteamManager initialized
Client (Round hadn't been started)

System info:
    Operating system: Microsoft Windows NT 10.0.19045.0 64 bit
    GPU name: NVIDIA GeForce GTX 1050 Ti
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal

Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateJobVariantTooltip(Barotrauma.JobPrefab, Barotrauma.CharacterTeamType, Int32, Boolean, Barotrauma.GUIComponent)
Stack trace: 
   at Barotrauma.NetLobbyScreen.CreateJobVariantTooltip(JobPrefab jobPrefab, CharacterTeamType team, Int32 variant, Boolean isPvPMode, GUIComponent parentSlot) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\NetLobbyScreen.cs:line 2808
   at Barotrauma.NetLobbyScreen.Update(Double deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\NetLobbyScreen.cs:line 4024
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 942
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 61

Last debug messages:
[10/22/2024 21:41:04] Lobby created!
[10/22/2024 21:40:28] WARNING: Tried to restore enabled packages multiple times/without performing a backup
[10/22/2024 21:40:20] Lobby created!
[10/22/2024 21:37:57] Attempting to open ALC device "OpenAL Soft on Speakers (HyperX Cloud Stinger Core Wireless DTS)"
[10/22/2024 21:37:54] Logged in as ruberine (SteamID STEAM_1:0:549660146)
