### ISSUE TITLE
NPCs cannot access damaged walls surrounding the docking hatch in Herja

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15378]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15261

<div type='discussions-op-text'>

<sup>Originally posted by **coldninja9** November 27, 2024</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

On the "Herja" submarine an NPC glitch occurs when the hull surrounding the docking hatch is damaged where NPC's will attempt to fix the hull but cannot access it. 

### Reproduction steps

1. Select "Herja" submarine
2. Assign any NPC to "fix leaks" 
3. Damage hull surrounding the docking port towards the top of the submarine
4. Observe

### Bug prevalence

Happens regularly

### Single player or multiplayer?

Single player

### Version

v1.6.19.1 (Unto the Breach Update Hotfix 2)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by JeroonBosch** [comment]
Before
https://github.com/user-attachments/assets/0f9fffda-bcd0-4c7f-bd68-724f21684694

After
https://github.com/user-attachments/assets/bc8de496-9a88-4c19-bdd2-e8ce53fc3b2f

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/pull/6311, closing

**Comment by NixisRD** [comment]
Writing this in hopes it will get reopened. The bug is still present. Adding to the orginial post, this also happens in singleplayer, multiplayer and editor.

**Comment by JeroonBosch** [comment]
> Writing this in hope, that it will get reopened. The bug is still present. Adding to the orginial post, this also happens in singleplayer, multiplayer and editor.

The update is not live yet. Is the bug present on unstable?
