### ISSUE TITLE
Overriding Crawler_hatchling will break its sprite

### ISSUE THREAD

**Issue by Regalis11** [FakeFishGames/Barotrauma#15502]
### Discussed in https://github.com/FakeFishGames/Barotrauma/discussions/15481

<div type='discussions-op-text'>

<sup>Originally posted by **A2ur3** January  6, 2025</sup>
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

```xml
<Override>
  <Charactervariant inherit="Crawler" speciesname="Crawler_hatchling" speciestranslationoverride="Crawler" texture="Content/Characters/Variants/Crawler_hatchling/crawlerhatchling.png" eatingspeed="1">
    <health vitality="40"/>
    <ragdoll scalemultiplier="0.5" texturescale="1.0" sourcerectscale="0.5"/>
    <attack damagemultiplier="0.5" rangemultiplier="0.5" impactmultiplier="0.5" />
    <animations folder="Content/Characters/Variants/Crawler_hatchling/Animations/"/>
    <ai combatstrength="50">
      <target tag="crawlerbroodmother" state="Protect" priority="10" reactdistance="500" ignoreinside="true"/>
      <target tag="crawler_large" state="Protect" priority="5" reactdistance="500" ignoreinside="true"/>
      <target tag="crawler" state="Protect" priority="2" reactdistance="500" ignoreinside="true"/>
      <target tag="dead" state="Eat" priority="1" />
    </ai>
    <inventory/>
  </Charactervariant>
</Override>
```

### Reproduction steps

Override Crawler_hatchling without changing anything

### Bug prevalence

Just once

### Single player or multiplayer?

Single player

### Version

v1.7.7.0 (Winter Update)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

_No response_</div>

**Comment by Regalis11** [comment]
Fixed in https://github.com/FakeFishGames/Barotrauma-development/commit/92a102435631b010b264c11cd8f7bbcd59c238ac

**Comment by Regalis11** [comment]
Merged, closing

**Comment by JeroonBosch** [comment]
This is not fixed, according to discord user D

![Image](https://github.com/user-attachments/assets/6d63b286-ab41-436e-ae4f-8ea90fcc0d60)
